### ISSUE TITLE
Uncaught TypeError: Ember.getOwner(...).factoryFor is not a function within init() method of the service

### ISSUE THREAD

**Issue by nikdojo** [gmurphey/ember-config-service#46]
Hi!

Using v0.2.0 with ember-cli@3.1.4. Getting the following issue:

`Uncaught TypeError: Ember.getOwner(...).factoryFor is not a function` pointing to init() method of `ember-config-service/services/config`:

```Ember.set(this, 'content', Ember.getOwner(this).factoryFor('config:environment').class);```

The same code I wrote as a fix before the service was updated to not use deprecated `_lookupFactory`, it worked fine.

Any ideas? Thx.

**Comment by gmurphey** [comment]
Looking at the app blueprint from `ember-cli@3.1.4`, it looks like it's using `ember-source@3.1.0` by default. Please make sure to use `ember-source@3.1.1` or higher. There was a issue in `3.1.0` with proxy objects and `getOwner`.

**Comment by nikdojo** [comment]
@gmurphey Yeah! Thx a lot, man. That was really a reason, it has to be at least 3.1.1.

Cheers!
